# Generated by Django 2.1.2 on 2018-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=256, unique=True)),
                ('height', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'infnote_migration',
            },
        ),
    ]
