# Generated by Django 2.0.5 on 2018-06-06 09:23

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(db_column='_id', default=None, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255, unique=True)),
                ('private_key', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_confirmed', models.DateTimeField(null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('gender', models.IntegerField(choices=[(0, 'unknown'), (1, 'male'), (2, 'female')], default=0)),
                ('date_birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('qq', models.CharField(blank=True, max_length=50)),
                ('wechat', models.CharField(blank=True, max_length=50)),
                ('weibo', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('topics', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'infnote_users',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('expires', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'infnote_vcode',
            },
        ),
    ]
