# Generated by Django 2.1.1 on 2018-09-23 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('public_key', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('avatar', models.CharField(max_length=256, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'unknown'), (1, 'male'), (2, 'female')], default=0)),
                ('bio', models.CharField(blank=True, max_length=256)),
                ('signature', models.CharField(max_length=100, null=True)),
                ('topics', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'infnote_users',
            },
        ),
        migrations.CreateModel(
            name='NonceToken',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('nonce', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=256)),
                ('date_expired', models.DateTimeField(default=datetime.datetime(2018, 9, 23, 9, 17, 5, 467949, tzinfo=utc))),
            ],
        ),
    ]
