# Generated by Django 2.0.6 on 2018-07-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_txid',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='info_txid',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
