# Generated by Django 2.0.5 on 2018-06-13 14:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(db_column='_id', default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('display_name', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('topics', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'infnote_categories',
            },
        ),
    ]
