# Generated by Django 2.0.6 on 2018-06-25 10:55

from django.db import migrations


def initial_bt_info(apps, _):
    Info = apps.get_model('blockchain', 'Info')
    Info.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_bt_info)
    ]
