# Generated by Django 2.1 on 2018-08-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20180625_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='spend_txid',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='height',
            field=models.BigIntegerField(default=0),
        ),
    ]
