# Generated by Django 2.0.5 on 2018-06-06 09:23

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(db_column='_id', default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.CharField(max_length=20000)),
                ('category', models.CharField(max_length=255)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_confirmed', models.DateTimeField(default=None, null=True)),
                ('transaction_id', models.CharField(max_length=128, null=True, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('block_height', models.IntegerField(default=0)),
                ('reply_to', models.CharField(db_index=True, max_length=128, null=True)),
                ('replies', models.IntegerField(default=0)),
                ('last_reply', models.CharField(max_length=128, null=True)),
                ('base_to', models.CharField(max_length=128, null=True)),
                ('public_key', models.CharField(max_length=128)),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'infnote_posts',
            },
        ),
    ]
