# Generated by Django 2.1 on 2018-08-20 06:54

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=20000)),
                ('user_id', models.CharField(max_length=100)),
                ('topic_id', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('time_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_to', models.CharField(db_index=True, max_length=128, null=True)),
                ('replies', models.IntegerField(default=0)),
                ('last_reply', models.CharField(max_length=128, null=True)),
                ('likes', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'infnote_posts',
            },
        ),
    ]
