# Generated by Django 2.1.1 on 2018-09-22 07:48

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=None, primary_key=True, serialize=False)),
                ('replies', models.IntegerField(default=0)),
                ('last_reply', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=20000)),
                ('signature', models.CharField(max_length=256)),
                ('user_id', models.CharField(max_length=100)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_to', models.CharField(db_index=True, max_length=256, null=True)),
                ('payload_id', models.CharField(max_length=256, unique=True, db_index=True)),
                ('date_confirmed', models.DateTimeField(default=None, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('block_height', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'infnote_posts',
            },
        ),
    ]
